### ISSUE TITLE
Mark 2.36.12 1004 as broken

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/gdk-pixbuf-feedstock#15]
When #14 is build and deployed we should ask core to mark the affected builds as broken.

**Comment by pkgw** [comment]
#14 has just been merged, so the deployed packages should be updating shortly.

**Comment by chrisburr** [comment]
@conda-forge/core Please can you mark the three `_1004` builds as broken?

https://anaconda.org/conda-forge/gdk-pixbuf/files

* `gdk-pixbuf-2.36.12-haf2c3b9_1004.tar.bz2`
* `gdk-pixbuf-2.36.12-h1308931_1004.tar.bz2`
* `gdk-pixbuf-2.36.12-haf2c3b9_1004.tar.bz2`

**Comment by jjhelmus** [comment]
> Please can you mark the three `_1004` builds as broken?

Done, can you verify that the correct files were marked.

**Comment by chrisburr** [comment]
That's perfect. Thanks @jjhelmus!
