### ISSUE TITLE
Need a way to update list of gdk-pixbuf loaders

### ISSUE THREAD

**Issue by pkgw** [conda-forge/gdk-pixbuf-feedstock#2]
Other packages can provide "loader" plugins that gdk-pixbuf can load dynamically, allowing it to process new image format files. But in order for gdk-pixbuf to know about these loaders, a special cache file must be updated when these packages are installed or uninstalled.

I believe that this means that packages that provide gdk-pixbuf loaders — like the newly-added `librsvg` — need `post-link` and `post-unlink` scripts to deal with updating the gdk-pixbuf loader cache.

In order to update the loader cache, one needs to execute a non-trivial bit of shell code. Below is what I have been using in my personal packages:

```shell
# Make sure that loaders.cache is fully up-to-date. I don't want to assume
# that pkg-config is available, so we hack a bit to avoid running it when we
# get the cache location. Or we could just glob or hardcode the binary version
# ...

set -e
eval $(grep -v : $PREFIX/lib/pkgconfig/gdk-pixbuf-2.0.pc)
if [ -z "$gdk_pixbuf_cache_file" ] ; then
    bindir="$(echo $PREFIX/lib/gdk-pixbuf-2.0/*)"
    if [ ! -d $bindir ] ; then
       echo >&2 "error: no such gdk-pixbuf binary directory $PREFIX/lib/gdk-pixbuf-2.0/*"
       exit 1
    fi
    gdk_pixbuf_cache_file=$bindir/loaders.cache
fi
$PREFIX/bin/gdk-pixbuf-query-loaders >$gdk_pixbuf_cache_file
```

I think that gdk-pixbuf should provide this bit of shell script so that not every dependent package needs to embed the same logic ­— that way, if the script needs changing, all that needs to happen is to update the gdk-pixbuf package itself.

By the same logic, I think that the above script should just be provided as gdk-pixbuf's own `post-link` and `post-unlink` scripts. Other packages can then just pass off responsibility on to it:

```shell
exec $PREFIX/bin/.gdk-pixbuf-post-link.sh
```

I can prepare a PR if this sounds like a good plan.

**Comment by jefftrull** [comment]
That would have helped this n00b today

**Comment by pkgw** [comment]
Wait a minute, I fixed this! This functionality is now available.
