### ISSUE TITLE
Unable to install for other platforms

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/gdk-pixbuf-feedstock#23]
When installing for a different platform (or cross-compiling with conda-build) installing the environment fails:

```bash
$ CONDA_SUBDIR=linux-ppc64le conda create --name test gdk-pixbuf
.....
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::gdk-pixbuf-2.38.2-hb6602f3_4'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::gdk-pixbuf-2.38.2-hb6602f3_4
location of failed script: /home/cburr/miniconda3/envs/test/bin/.gdk-pixbuf-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: /home/cburr/miniconda3/envs/test/bin/.gdk-pixbuf-post-link.sh: line 21: /home/cburr/miniconda3/envs/test/bin/gdk-pixbuf-query-loaders: cannot execute binary file: Exec format error

return code: 126

()

```

This is due to the post link script and to avoid this the [conda-build docs state](https://conda.io/projects/conda-build/en/latest/resources/link-scripts.html):

> Post-link and pre-unlink scripts should:
>  * Depend only on simple system tools such as rm, cp, mv, and ln.

I've not looked into the details yet but is there any way running `gdk-pixbuf-query-loaders` can be avoided?

**Comment by pkgw** [comment]
@chrisburr The query-loaders program is part of gdk-pixbuf's infrastructure to support plugins that extend its ability to load different types of images. It looks for shared libraries in a plugin directory and uses them to generate a data file that the main code uses to decide how to handle different input files.

Anyway, it is good to run the program, but the core image formats will work without needing to run it, so probably we should just try running it and ignore the error if it doesn't work. If Conda is going to let you set up environments on a foreign architecture on which you can't actually run executables, I'm not sure what other option there is.

**Comment by chrisburr** [comment]
Thanks for the prompt response. Letting it fail seems like a clean enough solution, especially considering it's still partially functional and can print a message explaining what should be done.

I've opened a PR with a suggested fix: https://github.com/conda-forge/gdk-pixbuf-feedstock/pull/24
